# pubspec.yaml
name: loginpage
description: "Gestor de Senhas"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  local_auth: ^2.1.2  # ✅ ATUALIZADO
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9  # ✅ ATUALIZADO
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0  # ✅ ATUALIZADO
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  analyzer: ^6.0.0  # ✅ JÁ ESTÁ AQUI, MAS VAMOS MUDAR

flutter:
  uses-material-design: true
  assets:
    - assets/